### ISSUE TITLE
duk_pcompile_string missing

### ISSUE THREAD

**Issue by brentp** [manguluka/duktape-nim#1]
hi, thanks for making this available. Is there any reason why https://duktape.org/api.html#duk_pcompile_string and some others are missing?

also, I have a small wrapper for your library that enables syntax like:
```Nim
      var kid = ctx.newObject("kid")
      kid["xyz"] = 22.31
      kid["asdf"] = 33.333
      check kid["xyz"] == 22.31
      check kid["asdf"] == 33.333
      kid["asdf"] = 33
      check kid["asdf"] == 33

      ctx["somevar"] = 22.33
      check ctx["somevar"] == 22.33
```

is there a place for this type of higher-level API inside of your module? If so, I'd be happy to contribute it.

**Comment by bingX4devX** [comment]
Many thanks for the contribution. No particular reason, just got pulled into other projects. 

A higher-level API would be great.
